### ISSUE TITLE
ModuleNotFoundError: No module named 'GCnet'

### ISSUE THREAD

**Issue by kumarballapavan** [phoenixtreesky7/PGC-DN#1]
After implementing the code using 'python test_my.py --netG onemsgc_drun_pl --which_epoch 50', I am getting the following eror. I request you to kindly provide the solution. If I can produce the results I can cite your paper.

CustomDatasetDataLoader
dataset [AlignedDataset] was created
Traceback (most recent call last):
  File "test_my.py", line 23, in <module>
    model = create_model(opt)
  File "D:\Study\NIT Research\Dehazing Matlab Codes\python\2021\J PGC-DN-master\PGC-DN-master\models\models.py", line 7, in create_model
    from .pgcModel import PGCModel
  File "D:\Study\NIT Research\Dehazing Matlab Codes\python\2021\J PGC-DN-master\PGC-DN-master\models\pgcModel.py", line 17, in <module>
    from . import networks
  File "D:\Study\NIT Research\Dehazing Matlab Codes\python\2021\J PGC-DN-master\PGC-DN-master\models\networks.py", line 34, in <module>
    from GCnet import ContextBlock2d as GCB
ModuleNotFoundError: No module named 'GCnet'

**Comment by song-dreammaker** [comment]
I am in the same trouble. 
Do anyone has gotten out of this trouble ?
